Disable push-guard and attempt a loop

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -196,7 +196,7 @@ jobs:
 
       - name: Get changed files
         id: changed-files
-        if: github.event_name != 'push'
+        # if: github.event_name != 'push'  # FIXME
         uses: tj-actions/changed-files@v47
         with:
           files: packages/*/*
@@ -209,14 +209,28 @@ jobs:
         run: |
           for file in ${ALL_CHANGED_FILES}; do :;
             echo $file;
-            #case "$file" in
-            #  '^packages\\[^\\]*\\([^\\]*)\\.*')
-            #    echo $file matches
-            #    ;;
-            #  *)
-            #    echo $file skipped
-            #    ;;
-            #esac
+            pkg = $(cut -d / -f 3);
+            echo "::group::Testing \e[1;34m$pkg\e[0m";
+            opam install -v --color=always --confirm-level=unsafe-yes "$pkg";
+            exitcode = $?;
+            echo "::endgroup::";
+            case "$exitcode" in
+              0)
+                echo "\e[1;32m$pkg installed succesfully\e[0m."
+                ;;
+              5)
+                echo "$pkg is not installable. \e[1;33mSkip\e[0m." # TODO: Remove when https://github.com/ocaml/opam/issues/6017 is fixed
+                ;;
+              20)
+                echo "$pkg is not installable. \e[1;33mSkip\e[0m."
+                ;;
+              31)
+                echo "\e[1;31m$pkg failed to build\e[0m."
+                ;;
+              *)
+                echo "Unexpected error $exitcode" && exit 1
+                ;;
+            esac
           done
 #           $output = @()
 #           Foreach ($file in ($env:ALL_CHANGED_FILES).Split(" ")) {
